# Generated by Django 6.1.1 on 2026-09-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='publication_yer',
            new_name='publication_year',
        ),
    ]
