# Generated by Django 6.1.1 on 2026-09-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_publication_yer_bookmodel_publication_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='available',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='ibsn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.authormodels'),
        ),
    ]
