# Generated by Django 6.1.1 on 2026-09-26 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_authormodels_alter_bookmodel_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authormodels',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='ibsn',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authormodels',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='publication_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1400), django.core.validators.MinValueValidator(2026)]),
        ),
    ]
