# Generated by Django 6.1.1 on 2026-09-26 03:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_authormodels_options_remove_bookmodel_ibsn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='publication_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1400), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
